#include <iostream>
using namespace std;
int main(){
    int sukupertama;
    int input;
    int beda;
    int hasil;
    int hasil1;
    int hasil2;
    int hasil3;
    int hasil4;
    int hasil5;


    cout << endl;
    cout <<endl;
    cout << "++++++++++++KALKULATOR BARIS ARITMATIKA++++++++++++++"<<endl<<endl;

    cout << "Suku pertama: "<<endl;
    cin >>sukupertama;

    cout << "Beda: "<<endl;
    cin >> beda;

    cout << "tentukan suku yang akan dicari: "<<endl;
    cin >> input;

    hasil= 2*sukupertama;
    hasil1= input-1;
    hasil2= hasil1+hasil2;
    hasil3= hasil2*beda;
    hasil4= input/2;
    hasil5= hasil3*hasil4;





    cout << hasil5;

}
