#include <iostream>
using namespace std;
int main ()
{
    int beda;
    int sukupertama;
    int input;
    int hasil;
    int hasil2;
    int hasil3;

    cout << endl;
    cout <<endl;
    cout << "++++++++++++KALKULATOR BARIS ARITMATIKA++++++++++++++"<<endl<<endl;

    cout << "Suku pertama: "<<endl;
    cin >>sukupertama;

    cout << "Beda: "<<endl;
    cin >> beda;

    cout << "tentukan suku yang akan dicari: "<<endl;
    cin >> input;

    hasil= input-1;
    hasil2= hasil*beda;
    hasil3=hasil2+sukupertama;

    cout << hasil3;









}
